# Generated by Django 5.0.6 on 2024-06-19 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_de_pacientes', '0002_alter_tratamientoactualizado_documento_afecciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_de_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='aparatos',
            field=models.ManyToManyField(blank=True, related_name='aparatos_en_el_paciente', to='registros_de_pacientes.unidad'),
        ),
    ]
