# Generated by Django 5.0.6 on 2024-06-19 08:50

import apps.utils.PathDirs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_de_pacientes', '0003_paciente_fecha_de_nacimiento_alter_paciente_aparatos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='documento',
        ),
        migrations.AddField(
            model_name='unidad',
            name='modelo_3d',
            field=models.FileField(default='default/default.txt', upload_to=apps.utils.PathDirs.path_dir_modelo_3d_unidad),
        ),
    ]
