# Generated by Django 5.0.6 on 2024-06-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros_de_pacientes', '0004_remove_unidad_documento_unidad_modelo_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='afecciones',
            name='id_afeccion',
            field=models.IntegerField(default=1),
        ),
    ]
