# Generated by Django 5.0.6 on 2024-06-21 00:53

import apps.utils.PathDirs
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloDentalEnviadoAComparar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_archivo', models.IntegerField(unique=True)),
                ('archivo_3d', models.FileField(upload_to=apps.utils.PathDirs.path_dir_modelo_dental_enviado)),
            ],
        ),
    ]
